on: [push]
name: Lint & Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}
      - name: Install Tools
        run: |
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          go install honnef.co/go/tools/cmd/staticcheck@master
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - uses: actions/checkout@v2
      - name: Build
        run: go build main.go

      - name: Vet
        run: |
          go vet -v ./...
          staticcheck ./...
          gosec ./...
          gocyclo -over 15 ./

      - name: Test
        run: |
          mkdir -p build
          go test -race -v ./... -count=1 -coverprofile=coverage.out -covermode=atomic

      - name: Coverage
        run: |
          go tool cover -html=build/coverage.out -o build/coverage.html
          gocov convert build/coverage.out | gocov-xml > build/coverage.xml

      #Coveritup
      - name: Code Coverage
        run: |
          curl -sLk https://raw.githubusercontent.com/kevincobain2000/cover-totalizer/master/install.sh | sh
          echo SCORE=`./cover-totalizer build/coverage.xml` >> "$GITHUB_ENV"

      - name: Go Binary Size
        run: |
          echo SCORE=`du -sk main | awk '{print $1}'` >> "$GITHUB_ENV"

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: go-binary-size

      - uses: kevincobain2000/action-coveritup@v1
        with:
          pr_comment: true

